name: Compute
markdown: redcarpet
pygments: true
permalink: none
compute_git_url: https://github.com/agordon/compute.git
compute_version: 1.0.3
compute_releases: https://github.com/agordon/compute/releases/
compute_src_tarball_filename: compute-1.0.3.tar.gz
compute_src_tarball_url: https://s3.amazonaws.com/agordon/compute/src/compute-1.0.3.tar.gz
compute_deb_64bit_url: https://s3.amazonaws.com/agordon/compute/bin/compute_1.0.3-1_amd64.deb
compute_rpm_64bit_url: https://s3.amazonaws.com/agordon/calc/bin/calc-1.0.1-1.el6.x86_64.rpm
compute_bin_linux_64bit_url: https://s3.amazonaws.com/agordon/compute/bin/compute-1.0.3-bin__Linux__x86_64.tar.gz
compute_bin_macosx_url: https://s3.amazonaws.com/agordon/compute/bin/compute-1.0.3-bin__MacOSX__x86_64.tar.gz
compute_bin_freebsd_64bit_url: https://s3.amazonaws.com/agordon/calc/bin/calc-1.0.1-bin__FreeBSD10__amd64.tar.gz
